### ISSUE TITLE
Question: Why cython

### ISSUE THREAD

**Issue by mkassner** [adamlwgriffiths/cyglfw3#15]
Cython is a great tool. In my mind it completes python. 

However, the installation procedure of cyglfw seems to require more attention than just installing glfw.
A ctypes binding of glfw is a single pure python file + libglfw - thats hard to beat in terms of simplicity.

In many cases the choice of cython over ctypes wins when granularity and performance are an issue. However, GLFW does not seem to be such a case.

This is not a critique of this project, I m just curious as to its motivation. 

(Also, this is the only actively maintained GLFW python binding. Others have stalled around GLFW3.0.4. )

**Comment by adamlwgriffiths** [comment]
I felt like playing around with it =P

GLFW calls are not made often and shouldn't present much of a problem for standard ctypes bindings.

**Comment by mkassner** [comment]
Thanks!
