### ISSUE TITLE
Building failed!

### ISSUE THREAD

**Issue by shuangyichen** [adamlwgriffiths/cyglfw3#25]
ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/envs/pvnet/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cff_tmg9/cyglfw3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cff_tmg9/cyglfw3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bcbaq0zv/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-cff_tmg9/cyglfw3/
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/__init__.py -> build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/compatible.py -> build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/version.py -> build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/glfw3.pyx -> build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/cglfw3.pxd -> build/lib.linux-x86_64-3.6/cyglfw3
    copying cyglfw3/glfw3.c -> build/lib.linux-x86_64-3.6/cyglfw3
    running build_ext
    building 'cyglfw3.glfw3' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cyglfw3
    gcc -pthread -B /root/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/pvnet/include/python3.6m -c cyglfw3/glfw3.c -o build/temp.linux-x86_64-3.6/cyglfw3/glfw3.o -I/usr/local/include -I/opt/local/include -I/opt/local/lib
    gcc -pthread -shared -B /root/anaconda3/envs/pvnet/compiler_compat -L/root/anaconda3/envs/pvnet/lib -Wl,-rpath=/root/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cyglfw3/glfw3.o -lglfw -o build/lib.linux-x86_64-3.6/cyglfw3/glfw3.cpython-36m-x86_64-linux-gnu.so -L/usr/local/lib
    /root/anaconda3/envs/pvnet/compiler_compat/ld: cannot find -lglfw
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/pvnet/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cff_tmg9/cyglfw3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cff_tmg9/cyglfw3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bcbaq0zv/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by adamlwgriffiths** [comment]
```/root/anaconda3/envs/pvnet/compiler_compat/ld: cannot find -lglfw```

**Comment by ameliamlz** [comment]
so how to solve this problem?

**Comment by shuangyichen** [comment]
> /root/anaconda3/envs/pvnet/compiler_compat/ld: cannot find -lglfw

But ld is not a directory. Where should I put glfw file? under compiler_compat? Thank you!
